name: Deploy Changed Lambdas to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Filter changed Lambda functions
        run: |
          CHANGED_LAMBDAS=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == */app.py ]]; then
              CHANGED_LAMBDAS+="$(dirname $file) "
            fi
          done
          # Remove duplicates and set output
          echo "changed=$(echo $CHANGED_LAMBDAS | tr ' ' '\n' | sort -u | tr '\n' ' ')" >> $GITHUB_ENV
      - name: Deploy changed Lambdas
        if: env.changed != ''
        run: |
          for lambda in ${{ env.changed }}; do
            cd $lambda
            zip -r ../$(basename $lambda).zip .
            cd ..
            echo "Deploying $lambda"
            aws lambda update-function-code \
              --function-name $(basename $lambda) \
              --zip-file fileb://$(basename $lambda).zip \
              --region us-west-2
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
